const learners = [
  { id: 'alex', initials: 'AH', name: 'Alex Harper', age: 23, meta: 'Lesson 12 · Junctions', progress: 68, status: 'On track', tone: 'olive' },
  { id: 'priya', initials: 'PS', name: 'Priya Shah', age: 31, meta: 'Lesson 8 · Independent driving', progress: 51, status: 'Needs focus', tone: 'peach' },
  { id: 'oliver', initials: 'OR', name: 'Oliver Reed', age: 18, meta: 'Lesson 21 · Mock test', progress: 86, status: 'Test ready', tone: 'lilac' },
  { id: 'mia', initials: 'MC', name: 'Mia Collins', age: 27, meta: 'Lesson 5 · Moving off', progress: 29, status: 'Getting started', tone: 'butter' }
];
const topics = [
  { title: 'Controls & cockpit drill', focus: 'Set up for a safe, confident drive', objectives: ['Identify and set all primary controls before moving.', 'Explain why seating, mirrors and restraints affect safety.'], sequence: ['Welcome learner at the parked car; invite them to set up without help.', 'Use show-me / tell-me prompts to check the cockpit drill.', 'Ask the learner to explain each adjustment and its safety benefit.', 'Repeat the drill until it is calm, consistent and independent.'], errors: ['Skipping the handbrake or gear check', 'Poor mirror alignment', 'Starting the engine before the safety checks'], questions: ['What would you like to adjust before we move?', 'What can you see in each mirror?', 'How will you know the car is secure?'], exercise: 'Park, reset the cockpit and complete the drill twice: once with a prompt, once independently.' },
  { title: 'Moving off & stopping', focus: 'Build a repeatable routine for smooth starts', objectives: ['Move away safely on a quiet, level road.', 'Stop under control with effective observation.'], sequence: ['Brief the POM routine: prepare, observe, move.', 'Demonstrate one calm move-off and narrate the observations.', 'Coach the learner through five starts, reducing prompts each time.', 'Add a controlled stop and secure the car after each repetition.'], errors: ['Rushing observations', 'Poor clutch biting-point control', 'Forgetting to secure the car after stopping'], questions: ['What is the car telling you through the clutch?', 'Where is the first safe gap?', 'What must you check before you release the brake?'], exercise: 'Complete five move-offs and stops, changing the stopping point each time.' },
  { title: 'Clutch control & gears', focus: 'Choose speed and gear with less workload', objectives: ['Find and hold the biting point smoothly.', 'Select a suitable gear for speed and road conditions.'], sequence: ['Find the biting point with the handbrake on.', 'Practise slow rolling, then add gentle acceleration.', 'Introduce upward and downward changes on a quiet route.', 'Review engine sound, road speed and forward planning.'], errors: ['Looking down at the gear lever', 'Holding the clutch down unnecessarily', 'Selecting a gear too early for the speed'], questions: ['What does the engine sound suggest?', 'What will the car need from you next?', 'Where can you complete the gear change safely?'], exercise: 'Use a loop with two stops, one hill and one turn; name the gear choice before each event.' },
  { title: 'Mirrors & blind spots', focus: 'Make information gathering purposeful', objectives: ['Use mirrors before changing speed, direction or position.', 'Understand what mirrors cannot show.'], sequence: ['Compare the view from each mirror while stationary.', 'Practise a mirror routine before simple speed changes.', 'Add a blind-spot check before moving around parked vehicles.', 'Review whether each glance changed the decision.'], errors: ['Checking mirrors without acting on information', 'Overlong mirror glances', 'Missing the blind spot before moving off'], questions: ['What changed since your last check?', 'How does that information affect your plan?', 'Which area cannot be covered by the mirrors?'], exercise: 'On a quiet road, call out the information you need before each planned speed or position change.' },
  { title: 'Junctions', focus: 'Approach with time, space and a clear plan', objectives: ['Choose a safe speed and position on approach.', 'Make effective observations before emerging or turning.'], sequence: ['Map the approach: mirrors, position, speed, look, decide.', 'Demonstrate one open and one closed junction.', 'Coach the learner through increasing complexity.', 'Use a quiet pause after each junction to review the decision.'], errors: ['Approaching too fast to look safely', 'Late signal or poor position', 'Emerging before the road is clear'], questions: ['What can you see and what remains hidden?', 'What is your safest speed for the view?', 'What would make you wait?'], exercise: 'Find three junctions with different levels of visibility and compare the approach plan.' },
  { title: 'Roundabouts', focus: 'Read traffic flow and choose safe gaps', objectives: ['Approach in the correct lane and at a safe speed.', 'Observe, decide and commit without hesitation.'], sequence: ['Review signs, lane markings and exit signals.', 'Demonstrate a simple left-turn roundabout.', 'Practise straight-ahead and right-turn routes with commentary.', 'Review lane discipline and exit timing.'], errors: ['Entering without a clear gap', 'Late lane change', 'Signalling too early or too late'], questions: ['Which lane takes you to that exit?', 'Where is your decision point?', 'What traffic could affect your chosen gap?'], exercise: 'Complete the same roundabout three ways, naming the lane, gap and exit signal beforehand.' },
  { title: 'Manoeuvres', focus: 'Slow, observe and adjust deliberately', objectives: ['Control the vehicle accurately at low speed.', 'Use effective all-round observation while manoeuvring.'], sequence: ['Choose a low-risk location and set a clear stopping point.', 'Demonstrate one manoeuvre with commentary.', 'Let the learner plan the reference points aloud.', 'Pause, reset and repeat with fewer prompts.'], errors: ['Moving too quickly', 'Focusing only on the kerb', 'Failing to stop and reassess'], questions: ['What can you not see right now?', 'What is the next safe adjustment?', 'Would a pause make this easier?'], exercise: 'Complete two attempts, with the learner choosing when to pause and reset.' },
  { title: 'Dual carriageways', focus: 'Plan ahead at higher speeds', objectives: ['Join, travel and leave safely at speed.', 'Maintain awareness of following traffic and developing hazards.'], sequence: ['Plan the route and identify joining and leaving points.', 'Discuss acceleration lanes and mirror checks.', 'Coach a joining sequence, then build independent commentary.', 'Review speed, following distance and exit preparation.'], errors: ['Joining too slowly', 'Staying in the wrong lane', 'Preparing for the exit too late'], questions: ['What information do you need before joining?', 'Where will you be in the next 20 seconds?', 'When will you start preparing for the exit?'], exercise: 'Use one short dual carriageway section and ask for a running plan before each change.' },
  { title: 'Independent driving', focus: 'Make safe decisions without step-by-step direction', objectives: ['Follow signs or a sat-nav while maintaining control.', 'Recover calmly when a direction is missed.'], sequence: ['Explain the route and agree that safety overrides navigation.', 'Start with a short sign-led section.', 'Add a sat-nav instruction and allow natural decisions.', 'Review planning, resilience and missed-direction recovery.'], errors: ['Prioritising the route over safety', 'Late lane changes', 'Freezing after a missed turn'], questions: ['What is the safest option now?', 'What information can wait?', 'How will you recover if you miss that turn?'], exercise: 'Drive a ten-minute route with only destination prompts; review three decisions afterwards.' }
];

const $ = (selector) => document.querySelector(selector);
const toast = (message) => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); };
const avatarClass = (tone) => `avatar avatar-${tone}`;
function renderLearners() { $('#learnerList').innerHTML = learners.map((learner) => `<div class="learner-row" data-learner="${learner.id}"><span class="${avatarClass(learner.tone)}">${learner.initials}</span><div><span class="learner-name">${learner.name}</span><span class="learner-meta">${learner.age} years · ${learner.meta}</span></div><div class="progress-mini"><em style="width:${learner.progress}%"></em></div><span class="learner-progress">${learner.progress}%</span></div>`).join(''); document.querySelectorAll('[data-learner]').forEach((row) => row.addEventListener('click', () => openLearnerDetail(row.dataset.learner))); }
function openLearnerDetail(id) { const learner = learners.find((item) => item.id === id) || learners[0]; $('#detailAvatar').textContent = learner.initials; $('#detailName').textContent = learner.name; $('#detailMeta').textContent = `${learner.age} years · Working towards a confident first test`; $('#learnerDetailBackdrop').hidden = false; lucide.createIcons(); }
function renderTopics(filter = '') { const filtered = topics.filter((topic) => topic.title.toLowerCase().includes(filter.toLowerCase())); $('#topicList').innerHTML = filtered.map((topic, index) => `<button class="topic-card ${index === 0 ? 'selected' : ''}" data-topic="${topics.indexOf(topic)}"><span class="topic-index">${String(topics.indexOf(topic) + 1).padStart(2, '0')}</span><span><strong>${topic.title}</strong><small>${topic.focus}</small></span><span data-lucide="arrow-up-right"></span></button>`).join('') || '<div class="panel"><p class="lede">No topic matches that search.</p></div>'; document.querySelectorAll('[data-topic]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.topic-card').forEach((card) => card.classList.remove('selected')); button.classList.add('selected'); renderTopicDetail(topics[button.dataset.topic]); })); if (filtered.length) renderTopicDetail(filtered[0]); lucide.createIcons(); }
function renderTopicDetail(topic) { $('#topicDetail').innerHTML = `<p class="eyebrow">Micro-plan · ${String(topics.indexOf(topic) + 1).padStart(2, '0')}</p><h2>${topic.title}</h2><p class="intro">${topic.focus}. Use this sequence as a starting point, then adapt your coaching to the learner in front of you.</p><div class="micro-sections"><section class="micro-section"><h3>Learning objectives</h3><ul>${topic.objectives.map((item) => `<li>${item}</li>`).join('')}</ul></section><section class="micro-section"><h3>Typical learner errors</h3><ul>${topic.errors.map((item) => `<li>${item}</li>`).join('')}</ul></section><section class="micro-section"><h3>Teaching sequence</h3><ul>${topic.sequence.map((item) => `<li>${item}</li>`).join('')}</ul></section><section class="micro-section"><h3>Coaching questions</h3><ul>${topic.questions.map((item) => `<li>${item}</li>`).join('')}</ul></section><section class="micro-section exercise"><h3>Short practice exercise</h3><p>${topic.exercise}</p></section></div>`; }
function switchView(view) { document.querySelectorAll('.view').forEach((section) => section.classList.remove('active-view')); $(`#${view}View`).classList.add('active-view'); document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.view === view)); $('#pageTitle').textContent = view === 'overview' ? 'Overview' : view === 'plans' ? 'Lesson plans' : 'Micro-plans'; window.scrollTo({ top: 0, behavior: 'smooth' }); }
function setupVoiceCapture() { const button = $('#captureBtn'); const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; let listening = false; let recognition; if (SpeechRecognition) { recognition = new SpeechRecognition(); recognition.continuous = true; recognition.interimResults = true; recognition.onresult = (event) => { const text = Array.from(event.results).map((result) => result[0].transcript).join(' '); button.dataset.transcript = text; }; recognition.onend = () => { if (listening) recognition.start(); }; } button.addEventListener('click', () => { if (!SpeechRecognition) { toast('Voice capture needs Chrome or Edge microphone access.'); return; } listening = !listening; button.classList.toggle('recording', listening); button.innerHTML = listening ? '<span data-lucide="square"></span>Stop & save note' : '<span data-lucide="mic"></span>Start voice note'; lucide.createIcons(); if (listening) { recognition.start(); toast('Listening. Speak your lesson note naturally.'); } else { recognition.stop(); toast(button.dataset.transcript ? 'Voice note captured and ready for your next lesson page.' : 'No speech detected yet.'); } }); }
function setupModal() { const backdrop = $('#modalBackdrop'); const detailBackdrop = $('#learnerDetailBackdrop'); $('#newLearnerBtn').addEventListener('click', () => { backdrop.hidden = false; }); $('#modalClose').addEventListener('click', () => { backdrop.hidden = true; }); $('#learnerDetailClose').addEventListener('click', () => { detailBackdrop.hidden = true; }); backdrop.addEventListener('click', (event) => { if (event.target === backdrop) backdrop.hidden = true; }); detailBackdrop.addEventListener('click', (event) => { if (event.target === detailBackdrop) detailBackdrop.hidden = true; }); $('#oneNoteBtn').addEventListener('click', () => toast('Open your Driving Instruction shortcut to continue in OneNote.')); $('#addLogBtn').addEventListener('click', () => toast('New lesson log entry ready to capture.')); $('#learnerForm').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.target); const name = data.get('name'); learners.unshift({ id: name.toLowerCase().replace(/\\s+/g, '-'), initials: name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(), name, age: data.get('age') || 17, meta: 'Lesson 1 · Getting started', progress: 5, status: 'Getting started', tone: 'mint' }); renderLearners(); backdrop.hidden = true; event.target.reset(); toast(`${name} added to your learners.`); }); }
document.addEventListener('DOMContentLoaded', () => { renderLearners(); renderTopics(); lucide.createIcons(); document.querySelectorAll('.nav-item').forEach((item) => item.addEventListener('click', () => switchView(item.dataset.view))); $('#viewAllBtn').addEventListener('click', () => toast('Learner directory is ready for your next update.')); $('#duplicatePlanBtn').addEventListener('click', () => toast('Template duplicated. Give this lesson a number and student.')); $('#savePlanBtn').addEventListener('click', () => toast('Lesson plan saved to this browser.')); $('#topicSearch').addEventListener('input', (event) => renderTopics(event.target.value)); setupVoiceCapture(); setupModal(); });
